### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by armenbagdasarov** [DenisBrunet/Cartool#15]
Hi Denis! Armen here. The newest version of Cartool keeps crashing on me. For example, when backfitting microstates, right after I load the template file, Cartool crashes. Turns out that if I add the EEG files first, then load the template file, it runs. But then again crashes in the middle of backfitting. There is no error message, it just closes out. I am not sure why this is happening! I restarted my computer to make sure it was not my computer causing problems, and the problem persists. I attached a video of the first example where it crashes after uploading the template file.

https://github.com/user-attachments/assets/510d42c4-d1ba-4d57-b936-31b829148afa

**Comment by armenbagdasarov** [comment]
Here's the second example of crashing when I load the files first and then the template file. It just shows the end since I cannot upload a large file here. 

https://github.com/user-attachments/assets/50862590-3124-4218-b161-e3d6924665ae

**Comment by DenisBrunet** [comment]
Hi Armen
I will have a look..

**Comment by DenisBrunet** [comment]
OK, I think I found the culprit for the crashes. Indeed that was on the opening and browsing the EEGs, for some specific cases. Introduced 17th of december, so hopefully not too many people will be affected. It's fixed, but I am now double checking on the remaining issues.
I keep you in touched.

**Comment by DenisBrunet** [comment]
Bug should be fixed, see release 5.04 and tell me...

**Comment by armenbagdasarov** [comment]
It is still crashing with 5.04 :( 

https://github.com/user-attachments/assets/cb49d2f9-7b02-4f33-aee3-6d26eee0995c

**Comment by DenisBrunet** [comment]
Hi Armen,
OK, I got it this time, bug is fixed!
I am going to look at the other issues before publishing an update, though. Keep you informed..
Denis

**Comment by armenbagdasarov** [comment]
Tested this and all works well. Feel free to close this issue. Thank you!
